config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'categories#default'
  resources :categories do
    get 'default', on: :member
    resources :books, only: :index
  end
  resources :books do
    resources :reviews, only: :create
  end
  resources :addresses
  resources :order_items, except: :show
  resources :coupons, only: :create
  resources :orders do
    get 'confirm', on: :member
  end
  resources :order_steps, only: %i(show update)

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  scope :newest,      ->(num) { order('created_at DESC').limit(num) }
  scope :bestsellers, ->(num) do
    joins('LEFT JOIN order_items ON order_items.book_id = books.id')
      .group('books.id')
      .order('count(order_items.book_id) DESC, books.created_at DESC')
      .limit(num)
  end

  belongs_to :category
  has_one    :book_dimension, dependent: :destroy
  has_many   :book_materials
  has_many   :book_authors
  has_many   :reviews
  has_many   :materials, through: :book_materials
  has_many   :authors, through: :book_authors
  has_many   :order_items
  has_many   :orders, through: :order_items
  has_many   :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images
  accepts_nested_attributes_for :book_dimension

  DEFAULT_PER = 12
  DEFAULT_IMAGE_NAME = 'book_default.jpg'
  DEFAULT_SORT_KEY = :titleA
  ORDERING = {
    priceA: 'price ASC',
    priceD: 'price DESC',
    new:    'created_at DESC',
    titleA: 'name ASC',
    titleD: 'name DESC'
  }.freeze

  validates_presence_of :name, :price, :publication_year
  validates_numericality_of :publication_year, only_integer: true, greater_than: 0
  validates_length_of :description, maximum: 1000
  validates_format_of :price, with: /\A\d+(?:\.\d{0,2})?\z/
  validates_format_of :name, with: /\A[-a-z !?,.@:=&'"]+\z/i
  validate :valid_year

  after_save :increment_books_count
  after_destroy :decrement_books_count

  def self.default_sort
    ORDERING[DEFAULT_SORT_KEY]
  end

  private

  def valid_year
    return unless Date.current.year < publication_year.to_i
    errors.add(:publication_year, I18n.t('flashes.error.wrong_year'))
  end

  def increment_books_count
    category.increment!(:count_books)
  end

  def decrement_books_count
    category.decrement!(:count_books)
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  helper_method :book_params

  load_resource :category
  load_resource :book, only: :show
  load_and_authorize_resource through: :category, only: :index, if: -> { !@category.nil? }
  load_and_authorize_resource only: :index, if: -> { @category.nil? }

  def index
    @paginator = PaginatorService.new(params, @category)
    @books = @books.order(ordering).limit(@paginator.limiting)
  end

  def show
    @reviews = @book.reviews.approved.decorate
  end

  private

  def ordering
    order = book_params.key?(:order) ? book_params[:order].to_sym : nil
    Book::ORDERING.key?(order) ? Book::ORDERING[order] : Book.default_sort
  end

  def book_params
    params.permit(:page, :id, :order)
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
  def category_sort_present?
    params.key?(:order) && Book::ORDERING[params[:order].to_sym].present?
  end

  def current_sorting
    return params[:order] if category_sort_present?
    Book::DEFAULT_SORT_KEY
  end

  def current_catalog_name
    @category.nil? ? 'All' : @category.name
  end
end

app/views/books/catalog/_by_categories_desktop.html.haml
%ul.list-inline.pt-10.mb-25.mr-240
  %li.mr-35
    = link_to(books_path, class: 'filter-link') do
      = t('books.catalog.all')
      %span.badge.general-badge= Category.sum(:count_books)
  - active_categories.each do |category|
    %li.mr-35
      = link_to(category_books_path(category), class: 'filter-link') do
        = category.name
        %span.badge.general-badge
          = category.count_books

app/views/books/catalog/_by_categories_mobile.html.haml
.dropdown
  %a.dropdown-toggle.lead.small{href: '#', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false'}
    = current_catalog_name
    %i.fa.fa-angle-down.dropdown-icon.pull-right
  %ul.dropdown-menu
    %li
      = link_to t('books.catalog.all'), books_path
    - active_categories.each do |category|
      %li
        = link_to category.name, category_books_path(category)

app/views/books/catalog/_sorting.html.haml
%a.dropdown-toggle.lead.small{href: '#', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false'}
  = t("books.sorting.#{current_sorting}")
  %i.fa.fa-angle-down.dropdown-icon.pull-right
%ul.dropdown-menu
  %li
  - Book::ORDERING.each do |value, _|
    %li
      = link_to t("books.sorting.#{value}"), book_params.merge(order: value)