config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'categories#default'
  resources :categories do
    get 'default', on: :member
    resources :books, only: :index
  end
  resources :books do
    resources :reviews, only: :create
  end
  resources :addresses
  resources :order_items, except: :show
  resources :coupons, only: :create
  resources :orders do
    get 'confirm', on: :member
  end
  resources :order_steps, only: %i(show update)

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/views/layouts/headers/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: 'button', 'data-toggle': 'collapse', 'data-target': '#navbar'}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand= t('general.project_name')
      = link_to(order_items_path, class: 'shop-link pull-right visible-xs') do
        %span.shop-icon
          - unless empty_cart?
            %span.shop-quantity= purchases_count
    = link_to(order_items_path, class: 'shop-link pull-right hidden-xs') do
      %span.shop-icon
        - unless empty_cart?
          %span.shop-quantity= purchases_count
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': 'false'}
      .visible-xs
        %button.close{type: 'button', 'aria-label': 'Close'}
          %span{'aria-hidden': 'true'} &times;
        %ul.nav.navbar-nav
          %li
            %a{type: 'button', 'data-toggle': 'collapse', href: '#menu', 'aria-expanded': 'false', 'aria-controls': 'menu'}= t('layout.links.home')
            %ul#menu.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': 'false'}
              - active_categories.each do |category|
                %li
                  = link_to "#{category.name}", category_path(category), class: 'collapse-link'
          %li
            = link_to t('layout.links.home'), root_path
          = render 'layouts/headers/header_part'
      .hidden-xs
        %ul.nav.navbar-nav
          %li.dropdown.home
            %a.dropdown-toggle{href: '#', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false'}= t('layout.links.home')
            %ul.dropdown-menu
              - active_categories.each do |category|
                %li
                  = link_to "#{category.name}", category_path(category)
            %li
              = link_to t('layout.links.shop'), books_path
            = render 'layouts/headers/header_part'

app/views/layouts/headers/_header_part.html.haml
- if user_signed_in?
  %li.dropdown
    %a.dropdown-toggle{href: '#', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false'}= t('layout.links.profile')
    %ul.dropdown-menu
      %li
        = link_to(t('layout.links.settings'), edit_user_registration_path)
      %li
        = link_to(t('orders.my_orders'), orders_path)
      - if current_user.admin?
        %li
          = link_to(t('general.admin_panel'), rails_admin.dashboard_path)
      %li.divider{role: 'separator'}
      %li
        = link_to(t('layout.links.logout'), destroy_user_session_path, :method => :delete)
- else
  %li
    = link_to(t('layout.links.login'), new_user_session_path)
  %li
    = link_to(t('layout.links.signup'), new_user_registration_path)