config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'categories#default'
  resources :categories do
    get 'default', on: :member
    resources :books, only: :index
  end
  resources :books do
    resources :reviews, only: :create
  end
  resources :addresses
  resources :order_items, except: :show
  resources :coupons, only: :create
  resources :orders do
    get 'confirm', on: :member
  end
  resources :order_steps, only: %i(show update)

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  include AASM

  has_many   :addresses, as: :addressable, dependent: :destroy
  has_many   :order_items, dependent: :destroy, after_add: :recalculate_total, after_remove: :recalculate_total
  has_many   :books, through: :order_items
  has_one    :coupon, dependent: :destroy
  belongs_to :card, dependent: :destroy
  belongs_to :user
  belongs_to :delivery

  before_create :set_track_number

  validates_length_of :track_number, maximum: 25

  MY_ORDERS_STATES = %i(in_confirmation in_processing in_delivery completed).freeze

  scope :in_carting, -> { where(aasm_state: %i(cart filled)) }
  scope :after_cart, -> { where(aasm_state: MY_ORDERS_STATES) }
  scope :newest, -> { order('created_at DESC') }
  scope :active, -> { where.not(aasm_state: :canceled) }

  aasm column: 'aasm_state' do
    state :cart, initial: true
    state :filled
    state :in_confirmation, after_enter: :send_confirmation
    state :in_processing, after_enter: :treat_proccessing
    state :in_delivery
    state :completed, after_enter: :send_success
    state :canceled

    event :filled do
      transitions from: :cart, to: :filled
    end

    event :in_confirmation do
      transitions from: :filled, to: :in_confirmation
    end

    event :treat do
      transitions from: :in_confirmation, to: :in_processing
    end

    event :to_deliver do
      transitions from: :in_processing, to: :in_delivery
    end

    event :complete do
      transitions from: :in_delivery, to: :completed
    end

    event :cancel do
      transitions from: %i(cart filled in_confirmation in_delivery in_processing completed), to: :canceled
    end
  end

  rails_admin do
    list do
      field :aasm_state, :state
      include_all_fields
      exclude_fields :confirmation_token, :completed_date
    end
    edit do
      field :aasm_state, :state
      include_all_fields
      exclude_fields :confirmation_token, :completed_date
    end
  end

  def self.default_sort
    ORDERING[DEFAULT_SORT_KEY]
  end

  %w[billing shipping].each do |type|
    define_method "#{type}_address" do
      addresses.find_by(kind: type)
    end
  end

  def valid_addresses?
    shipping_address && billing_address
  end

  def book_in_order?(book_id)
    !order_items.find_by(book: book_id).nil?
  end

  def subtotal_more_than_discount?(coupon)
    subtotal_price > coupon.discount
  end

  def send_confirmation
    update_attributes(confirmation_token: Devise.friendly_token)
    OrderMailer.confirmation_send(user, self).deliver_now
  end

  def treat_proccessing
    self.confirmation_token = nil
    OrderMailer.treating_send(user, self).deliver_now
  end

  def send_success
    OrderMailer.success_send(user, self).deliver_later
  end

  def recalculate_total(_)
    update_attributes(total_price: total_price)
  end

  def subtotal_price
    PricableService.subtotal_price(order_items)
  end

  def discount
    PricableService.discount(coupon)
  end

  def delivery_price
    PricableService.delivery_price(delivery)
  end

  def total_price
    PricableService.total_price(order_items, coupon, delivery)
  end

  def active?
    checkout_state? && order_items.present?
  end

  def proved?
    card && delivery && valid_addresses?
  end

  def checkout_state?
    cart? || filled?
  end

  def order_state?
    checkout_state? || in_confirmation?
  end

  def set_track_number
    self.track_number = "R-#{rand(99)}#{Date.today.to_time.to_i}"
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def index
    return redirect_to :root, alert: t('flashes.error.no_order') unless last_is_active?
    @purchases = last_order.order_items
  end

  def update
    user.order.in_confirmation.deliver
  end

  private

  def last_is_active?
    return unless last_order
    last_order.checkout_state? && !last_order(&:order_items).nil?
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  load_and_authorize_resource
  helper_method :order_params

  def index
    @orders = current_user.orders.after_cart
    @orders = @orders.send(order_params[:order].to_sym) if status_present?
  end

  def show
    @order = @order.decorate
  end

  def confirm
    if @order.confirmation_token == order_params[:token]
      @order.treat!
      flash.keep[:success] = I18n.t('orders.successfull')
    end
    redirect_to :root
  end

  private

  def order_params
    params.permit(:token, :order)
  end

  def status_present?
    return unless order_params[:order]
    Order::MY_ORDERS_STATES.include? order_params[:order].to_sym
  end
end

app/helpers/order_helper.rb
# frozen_string_literal: true

module OrderHelper
  def current_sort
    sort_present? ? params[:order].to_s.humanize : I18n.t('books.catalog.all')
  end

  def sort_present?
    return unless params.key? :order
    Order::MY_ORDERS_STATES.include? params[:order].to_sym
  end
end

app/views/order/index.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= t('general.cart')
  .visible-xs
    - @purchases.each do |purchase|
      = render 'order/tile/mobile', purchase: purchase
  .hidden-xs
    %table.table.table-hover
      %tr.no-hover
        %th.col-pic.pl-0
          %span.in-grey-600= t('orders.product')
        %th.col-title
        %th.col-price
          %span.in-grey-600= t('orders.price')
        %th.col-quantity
          %span.in-grey-600= t('orders.quantity')
        %th.col-total
          %span.in-grey-600= t('orders.subtotal')
        %th.col-close
      - @purchases.each do |purchase|
        = render 'order/tile/desktop', purchase: purchase
  .general-order-wrap
    .row
      .col-sm-4
        - if current_order.coupon.nil?
          = form_for :coupon, url: coupon_path, html: { method: :patch } do |f|
            .input-group.general-input-group
              = f.label :code, t('orders.coupon.enter_coupon') , class: 'input-label'
              = f.text_field :code, class:'form-control mb-30', placeholder: t('orders.coupon.enter_coupon')
              %div
                = f.submit t('orders.coupon.update_cart'), class: 'btn btn-primary mb-15 res-block'
      .col-sm-8
        .res-mr-200.text-center.general-text-right
          %p.in-gold-500.font-18= t('orders.order_summary')
          %table.general-summary-table.general-summary-table-right.general-text-right
            = render 'order_steps/price'
          = link_to t('orders.checkout'), order_step_path(id: :address), method: :get, class:'btn btn-default mb-20 visible-xs-inline-block'
  = link_to t('orders.checkout'), order_step_path(id: :address), method: :get, class:'btn btn-default w-20 mb-20 hidden-xs center-block'