config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'categories#default'
  resources :categories do
    get 'default', on: :member
    resources :books, only: :index
  end
  resources :books do
    resources :reviews, only: :create
  end
  resources :addresses
  resources :order_items, except: :show
  resources :coupons, only: :create
  resources :orders do
    get 'confirm', on: :member
  end
  resources :order_steps, only: %i(show update)

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/controllers/order_steps_controller.rb
# frozen_string_literal: true

class OrderStepsController < ApplicationController
  include Wicked::Wizard

  before_action :go_root_unless_order, :initialize_form

  steps :fast_sign, :address, :delivery, :payment, :confirm, :complete

  def show
    case step
    when :fast_sign then check_fast_sign and return
    when :address, :delivery, :payment then check_filling_steps and return
    when :confirm then check_confirm_step and return
    else check_complete_step
    end
  end

  def update
    @updating_result = @form.update(step, order_params)
    step_to next_step and return if @updating_result.eql?(true)
    render_wizard
  end

  private

  def order_params
    params.permit(:use_billing,
                  :delivery,
                  :success,
                  :editing,
                  shipping_address: %i[first_name last_name address city zip country phone kind],
                  billing_address:  %i[first_name last_name address city zip country phone kind],
                  card:             %i[card_number cvv expire_date name])
  end

  def initialize_form
    @form ||= OrderStepsForm.new last_active_order
  end

  def go_root_unless_order
    return if last_active_order(&:order_state?)
    redirect_to :root, alert: t('flashes.error.no_order')
  end

  def step_to(step)
    redirect_to wizard_path(step)
  end

  def check_fast_sign
    next_step and return if current_user
    render_wizard
  end

  def check_filling_steps
    step_to :fast_sign and return unless current_user
    step_to :complete and return if last_active_order.in_confirmation?
    step_to :confirm and return if last_active_order.filled? && !order_params[:editing].present?
    render_wizard
  end

  def check_confirm_step
    step_to :fast_sign and return unless current_user
    step_to :address and return unless last_active_order.valid_addresses?
    step_to :delivery and return unless last_active_order.delivery
    step_to :payment and return unless last_active_order.card
    last_active_order.filled! unless last_active_order.filled? || last_active_order.in_confirmation?
    render_wizard
  end

  def check_complete_step
    step_to :fast_sign and return unless current_user
    step_to :confirm and return unless last_active_order.in_confirmation?
    render_wizard
  end
end

app/views/order_steps/_address.html.haml
= form_tag wizard_path, class: 'res-mb-100', method: :patch do
  .hidden-xs.hidden-sm
    .row
      .col-md-5
        %h3.general-subtitle= t('users.addresses.billing_address')
        %p.general-info-text= t('orders.fields_required')
      .col-md-5.col-md-offset-1
        %h3.general-subtitle= t('users.addresses.shipping_address')
  .row
    .col-md-5.mb-40
      .visible-xs.visible-sm
        %h3.general-subtitle= t('users.addresses.billing_address')
        %p.general-info-text= t('orders.fields_required')
      = fields_for :billing_address, @form.billing_address do |f|
        = render 'forms/address_form', f: f, kind: :billing
    .col-md-5.col-md-offset-1.mb-60
      .visible-xs.visible-sm
        %h3.general-subtitle= t('users.addresses.shipping_address')
      .shipping-fields
        = fields_for :shipping_address, @form.shipping_address do |f|
          = render 'forms/address_form', f: f, kind: :shipping
      .form-group.checkbox
        %label.checkbox-label
          = check_box_tag :shipping_check, false, false, hidden: true, class: 'checkbox-input'
          %span.checkbox-icon
            %i.fa.fa-check
          %span.checkbox-text= t('orders.use_billing')
  .general-text-align.mb-60
    %p.in-gold-500.font-18= t('orders.order_summary')
    %table.general-summary-table
      %tr
        %td
          %p.font-16= t('orders.items_total')
        %td
          %p.font-16 €#{current_order.subtotal_price}
      %tr
        %td
          %p.font-16= t('orders.order_total')
        %td
          %p.font-16 €#{current_order.total_price}
    = submit_tag t('orders.save_and_continue'), class:'btn center-block mb-20'

app/views/order_steps/_complete.html.haml
.text-center.mb-40
  %h3.general-subtitle Thank You for your Order!
  %p.fw-300 An order confirmation has been has been sent to John Doe0411@gmail.com
.row.mb-20
  .col-sm-6
    .visible-xs
      %p.general-order-number.mb-0 Order #R25314582
      %p.general-address.mb-30 October 29, 2016
    %p.general-address
      John Doe
      %span.general-edit edit
      %br
      44 Fifth Ave v231
      %br
      New York NY 1001
      %br
      United States
      %br
      Phone +16507599755
  .col-sm-6.hidden-xs.text-right
    %p.general-order-number.mb-0 Order #R25314582
    %p.general-address.mb-30 October 29, 2016
.visible-xs
  .general-cart-item.divider-lg
    .general-img-wrap-table
      %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
    %p.title Android Programming for Beginners
    %P.in-grey-600.fw-300 A recipe-based book to help you efficiently create amazing PHP-based applications with Laravel 5.x
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500 €28.50
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          %span 1
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500 €32.90
  .general-cart-item.divider-lg.mb-55
    .general-img-wrap-table
      %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
    %p.title Android Programming for Beginners
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500 €28.50
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          %span 1
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500 €32.90
.hidden-xs.divider-lg.pt-20
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600 Book
        %th.col-method
        %th
          %span.in-grey-600 Price
        %th
          %span.in-grey-600 Quantity
        %th
          %span.in-grey-600 Total
    %tbody
      %tr
        %td
          .general-img-wrap-table
            %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
        %td
          %p.title Android Programming for Beginners
          %p.in-grey-600.fw-300 Maximize the potential of Bootstrap with a collection of real-world site projects for better, faster, more responsive web applications
        %td
          %span.font-16.in-gold-500 €28.50
        %td
          %span.ml-30 1
        %td
          %span.font-16.in-gold-500 €32.90
.text-center.general-text-right
  %p.in-gold-500.font-18 Order Summary
  %table.general-summary-table.general-summary-table-right.general-text-right
    %tr
      %td
        %p.font-16 Subtotal:
      %td
        %p.font-16 €117.69
    %tr
      %td
        %p.font-16 Coupon:
      %td
        %p.font-16 €0.00
    %tr
      %td
        %strong.font-18 Order Total:
      %td
        %strong.font-18 €117.69
.text-center
  %button.btn.btn-default.mb-20 Back to Store

app/views/order_steps/_confirm.html.haml
.row.mb-20
  .col-sm-3
    %h3.general-subtitle Shipping Address
    %p.general-address
      John Doe
      %span.general-edit edit
      %br
      44 Fifth Ave v231
      %br
      New York NY 1001
      %br
      United States
      %br
      Phone +16507599755
  .col-sm-3
    %h3.general-subtitle Billing Address
    %p.general-address
      John Doe
      %span.general-edit edit
      %br
      44 Fifth Ave v231
      %br
      New York NY 1001
      %br
      United States
      %br
      Phone +16507599755
  .col-sm-3
    %h3.general-subtitle Shipments
    %p.general-address
      Delivery Next Day!
      %span.general-edit edit
      %br
      By train
  .col-sm-3
    %h3.general-subtitle Payment Information
    %p.general-address
      ** ** ** 8756
      %span.general-edit edit
      %br
      12/2018
.visible-xs
  .general-cart-item.divider-lg
    .general-img-wrap-table
      %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
    %p.title Android Programming for Beginners
    %P.in-grey-600.fw-300 A recipe-based book to help you efficiently create amazing PHP-based applications with Laravel 5.x
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500 €28.50
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          %span 1
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500 €32.90
  .general-cart-item.divider-lg.mb-55
    .general-img-wrap-table
      %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
    %p.title Android Programming for Beginners
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500 €28.50
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          .input-group
            %a.input-link{href: "#"}
              %i.fa.fa-minus.line-heaght-40
            %input.form-control.quantity-input{type: "text"}
            %a.input-link{href: "#"}
              %i.fa.fa-plus.line-heaght-40
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500 €32.90
.hidden-xs.divider-lg.pt-20
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600 Book
        %th.col-method
        %th
          %span.in-grey-600 Price
        %th
          %span.in-grey-600 Quantity
        %th
          %span.in-grey-600 Total
    %tbody
      %tr
        %td
          .general-img-wrap-table
            %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
        %td
          %p.title Android Programming for Beginners
          %p.in-grey-600.fw-300 Maximize the potential of Bootstrap with a collection of real-world site projects for better, faster, more responsive web applications
        %td
          %span.font-16.in-gold-500 €28.50
        %td
          %span.ml-30 1
        %td
          %span.font-16.in-gold-500 €32.90
.text-center.general-text-right
  %p.in-gold-500.font-18 Order Summary
  %table.general-summary-table.general-summary-table-right.general-text-right
    %tr
      %td
        %p.font-16 Subtotal:
      %td
        %p.font-16 €117.69
    %tr
      %td
        %p.font-16 Coupon:
      %td
        %p.font-16 €0.00
    %tr
      %td
        %strong.font-18 Order Total:
      %td
        %strong.font-18 €117.69
.text-center
  %button.btn.btn-default.mb-20 Place Order

app/views/order_steps/_payment.html.haml
%h3.general-subtitle Credit Card
%form.max-600.mb-80
  .form-group.has-error
    %label.control-label.input-label{for: "cardNumber"} Card Number
    %input#cardNumber.form-control{type: "number", name: "cardnumber", placeholder: "Card Number"}
    %span.help-block Please enter a valid credit card number
  .row
    .col-sm-6
      .form-group
        %label.control-label.input-label{for: "cardName"} Name on Card
        %input#cardName.form-control{type: "text", name: "ccname", placeholder: "Name on Card"}
    .col-sm-3
      .form-group
        %label.control-label.input-label{for: "firstName"} MM / YY
        %input#firstName.form-control{name: "exp-date", type: "text", placeholder: "MM / YY"}
    .col-sm-3
      .form-group.relative
        %label.control-label.input-label{for: "firstName"} CVV
        %input#firstName.form-control{name: "cvc", type: "number", placeholder: "CVV"}
        %i.fa.fa-question-circle.general-form-help
.general-text-align
  %p.in-gold-500.font-18 Order Summary
  %table.general-summary-table
    %tr
      %td
        %p.font-16 Subtotal:
      %td
        %p.font-16 €117.69
    %tr
      %td
        %p.font-16 Coupon:
      %td
        %p.font-16 €0.00
    %tr
      %td
        %strong.font-18 Order Total:
      %td
        %strong.font-18 €117.69
.text-center
  %button.btn.btn-default.mb-80 Save and Continue

app/views/order_steps/_price.html.haml
%tr.items-total
  %td
    %p.font-16= t('orders.items_total')
  %td
    %p.pricable.font-16 €#{last_active_order.subtotal_price}
- if last_active_order.coupon
  %tr.coupon-price
    %td
      %p.font-16= t('coupon.title')
    %td
      %p.pricable.font-16 €#{last_active_order.discount}
- if last_active_order.delivery
  %tr.delivery-price
    %td
      %p.font-16= t('orders.delivery')
    %td
      %p.pricable.font-16 €#{last_active_order.delivery_price}
%tr.total-price
  %td
    %p.font-16= t('orders.order_total')
  %td
    %p.pricable.font-16 €#{last_active_order.total_price}

app/views/order_steps/address.html.haml
%main.container
  %h1.general-title-margin= t('orders.checkout')
  %ul.steps.list-inline
    - (wizard_steps - [:fast_sign]).each_with_index  do |checkout_step, number|
      - if current_step? checkout_step
        = link_to wizard_path(checkout_step), class: 'step active' do
          %span.step-number= number + 1
          %span.step-text.hidden-xs= checkout_step.capitalize
        %li.step-divider
      - else
        = link_to wizard_path(checkout_step, editing: true), class: 'step' do
          %span.step-number= number + 1
          %span.step-text.hidden-xs= checkout_step.to_s.capitalize
        %li.step-divider
  = form_tag wizard_path, class: 'res-mb-100', method: :patch do
    .hidden-xs.hidden-sm
      .row
        .col-md-5
          %h3.general-subtitle= t('users.addresses.billing_address')
          %p.general-info-text= t('orders.fields_required')
        .col-md-5.col-md-offset-1
          %h3.general-subtitle= t('users.addresses.shipping_address')
    .row
      .col-md-5.mb-40
        .visible-xs.visible-sm
          %h3.general-subtitle= t('users.addresses.billing_address')
          %p.general-info-text= t('orders.fields_required')
        = simple_fields_for :billing_address, @form.billing_address do |f|
          = render 'forms/address_form', f: f, kind: :billing
      .col-md-5.col-md-offset-1.mb-60
        .visible-xs.visible-sm
          %h3.general-subtitle= t('users.addresses.shipping_address')
        - if @form.order.use_billing
          .shipping-fields{style: 'display: none'}
            = simple_fields_for :shipping_address, @form.shipping_address do |f|
              = render 'forms/address_form', f: f, kind: :shipping
        - else
          .shipping-fields
            = simple_fields_for :shipping_address, @form.shipping_address do |f|
              = render 'forms/address_form', f: f, kind: :shipping
        .form-group.checkbox
          %label.checkbox-label
            = check_box_tag :use_billing, @form.order.use_billing, @form.order.use_billing, hidden: true, class: 'checkbox-input'
            %span.checkbox-icon
              %i.fa.fa-check
            %span.checkbox-text= t('orders.use_billing')
    .general-text-align.mb-60
      %p.in-gold-500.font-18= t('orders.order_summary')
      %table.general-summary-table
        = render 'order_steps/price'
      = submit_tag t('orders.save_and_continue'), class:'btn btn-default center-block mb-20'

app/views/order_steps/complete.html.haml
%main.container
  %h1.general-title-margin= t('orders.checkout')
  %ul.steps.list-inline
    - (wizard_steps - [:fast_sign]).each_with_index  do |checkout_step, number|
      - if current_step? checkout_step
        %a.step.active
          %span.step-number= number + 1
          %span.step-text.hidden-xs= checkout_step.capitalize
        %li.step-divider
      - else
        %a.step
          %span.step-number= number + 1
          %span.step-text.hidden-xs= checkout_step.to_s.capitalize
        %li.step-divider
  .text-center.mb-40
    %h3.general-subtitle= t('orders.thank_you')
    %p.fw-300
      #{t('orders.confirmation_send')} #{current_user.email}
  .row.mb-20
    .col-sm-6
      .visible-xs
        %p.general-order-number.mb-0
          #{t('layout.links.order')} #{last_order.track_number}
        %p.general-address.mb-30 October 29, 2016
      %p.general-address
        #{last_order.shipping_address.first_name}
        %br
        #{last_order.shipping_address.address}
        %br
        #{last_order.shipping_address.city} #{last_order.shipping_address.zip}
        %br
        #{last_order.shipping_address.country_name}
        %br
        Phone #{last_order.shipping_address.phone}
    .col-sm-6.hidden-xs.text-right
      %p.general-order-number.mb-0
        #{t('layout.links.order')} #{last_order.track_number}
      %p.general-address.mb-30 October 29, 2016
  .visible-xs
    - last_order.order_items.each do |item|
      .general-cart-item.divider-lg
        .general-img-wrap-table
          %img.cart-img-shadow{src: item.book.decorate.front_image, alt: "design-book"}
        %p.title= item.book.name
        %P.in-grey-600.fw-300= item.book.decorate.first_sentence_description
        %table.table
          %tr
            %td
              %span.in-grey-600= t('orders.price')
            %td
              %span.font-16.in-gold-500
                €#{item.book.price}
          %tr
            %td.vertical-middle
              %span.in-grey-600= t('orders.subtotal')
            %td
              %span= item.quantity
          %tr
            %td
              %span.in-grey-600= t('orders.subtotal')
            %td
              %span.font-16.in-gold-500
                €#{item.price_with_quantity}
  .hidden-xs.divider-lg.pt-20
    %table.table.table-hover
      %thead
        %tr
          %th
            %span.in-grey-600= t('general.book')
          %th.col-method
          %th
            %span.in-grey-600= t('orders.price')
          %th
            %span.in-grey-600= t('orders.quantity')
          %th
            %span.in-grey-600= t('orders.subtotal')
      %tbody
        - last_order.order_items.each do |item|
          %tr
            %td
              .general-img-wrap-table
                %img.cart-img-shadow.pull-left{src: item.book.decorate.front_image, alt: "design-book"}
            %td
              %p.title= item.book.name
              %p.in-grey-600.fw-300= item.book.decorate.first_sentence_description
            %td
              %span.font-16.in-gold-500
                €#{item.book.price}
            %td
              %span.ml-30= item.quantity
            %td
              %span.font-16.in-gold-500
                €#{item.price_with_quantity}
  .text-center.general-text-right
    %p.in-gold-500.font-18=t('orders.order_summary')
    %table.general-summary-table.general-summary-table-right.general-text-right
      = render 'order_steps/price'
  .text-center
    = link_to t('books.catalog.back_to_store'), root_path, class: 'btn btn-default mb-20'

app/views/order_steps/confirm.html.haml
%main.container
  %h1.general-title-margin= t('orders.checkout')
  %ul.steps.list-inline
    - (wizard_steps - [:fast_sign]).each_with_index  do |checkout_step, number|
      - if current_step? checkout_step
        = link_to wizard_path(checkout_step), class: 'step active' do
          %span.step-number= number + 1
          %span.step-text.hidden-xs= checkout_step.capitalize
        %li.step-divider
      - else
        = link_to wizard_path(checkout_step, editing: true), class: 'step' do
          %span.step-number= number + 1
          %span.step-text.hidden-xs= checkout_step.to_s.capitalize
        %li.step-divider
  .row.mb-20
    .col-sm-3
      %h3.general-subtitle= t('users.addresses.shipping_address')
      %p.general-address
        #{last_active_order.shipping_address.first_name} #{last_active_order.shipping_address.last_name}
        = link_to t('general.edit'), wizard_path(:address, editing: true), class:'general-edit'
        %br
        = last_active_order.shipping_address.address
        %br
        #{last_active_order.shipping_address.city} #{last_active_order.shipping_address.zip}
        %br
        = last_active_order.shipping_address.country_name
        %br
        Phone #{last_active_order.shipping_address.phone}
    .col-sm-3
      %h3.general-subtitle= t('users.addresses.billing_address')
      %p.general-address
        #{last_active_order.billing_address.first_name} #{last_active_order.billing_address.last_name}
        = link_to t('general.edit'), wizard_path(:address, editing: true), class:'general-edit'
        %br
        = last_active_order.billing_address.address
        %br
        #{last_active_order.billing_address.city} #{last_active_order.billing_address.zip}
        %br
        = last_active_order.billing_address.country_name
        %br
        = "#{t('general.phone')} #{last_active_order.shipping_address.phone}"
    .col-sm-3
      %h3.general-subtitle= t('orders.shipments')
      %p.general-address
        = last_active_order.delivery.title
        = link_to t('general.edit'), wizard_path(:delivery, editing: true), class:'general-edit'
        %br
        €#{last_active_order.delivery.price}
    .col-sm-3
      %h3.general-subtitle= t('orders.payment_info')
      %p.general-address
        = last_active_order.card.decorate.private_show
        = link_to t('general.edit'), wizard_path(:payment, editing: true), class:'general-edit'
        %br
        = last_active_order.card.expire_date
  .visible-xs
    - last_active_order.order_items.each do |item|
      .general-cart-item.divider-lg
        .general-img-wrap-table
          %img.cart-img-shadow{src: item.book.decorate.front_image, alt: "design-book"}
        %p.title= item.book.name
        %P.in-grey-600.fw-300= item.book.decorate.first_sentence_description
        %table.table
          %tr
            %td
              %span.in-grey-600= t('orders.price')
            %td
              %span.font-16.in-gold-500 €#{item.book.price}
          %tr
            %td.vertical-middle
              %span.in-grey-600= t('orders.quantity')
            %td
              %span= item.quantity
          %tr
            %td
              %span.in-grey-600= t('orders.subtotal')
            %td
              %span.font-16.in-gold-500 €#{item.price_with_quantity}
  .hidden-xs.divider-lg.pt-20
    %table.table.table-hover
      %thead
        %tr
          %th
            %span.in-grey-600= t('general.book')
          %th.col-method
          %th
            %span.in-grey-600= t('orders.price')
          %th
            %span.in-grey-600= t('orders.quantity')
          %th
            %span.in-grey-600= t('orders.total_price')
      %tbody
        - last_active_order.order_items.each do |item|
          %tr
            %td
              .general-img-wrap-table
                %img.cart-img-shadow.pull-left{src: item.book.decorate.front_image, alt: "design-book"}
            %td
              %p.title= item.book.name
              %p.in-grey-600.fw-300= item.book.decorate.first_sentence_description
            %td
              %span.font-16.in-gold-500 €#{item.book.price}
            %td
              %span.ml-30= item.quantity
            %td
              %span.font-16.in-gold-500 €#{item.price_with_quantity}
  .text-center.general-text-right
    %p.in-gold-500.font-18= t('orders.order_summary')
    %table.general-summary-table.general-summary-table-right.general-text-right
      = render 'order_steps/price'
  .text-center
    = link_to t('orders.save_and_continue'), order_step_path(:confirm, success: 'true'), class:'btn btn-default mb-20', method: :patch

app/views/order_steps/delivery.html.haml
%main.container
  %h1.general-title-margin= t('orders.checkout')
  %ul.steps.list-inline
    - (wizard_steps - [:fast_sign]).each_with_index  do |checkout_step, number|
      - if current_step? checkout_step
        = link_to wizard_path(checkout_step), class: 'step active' do
          %span.step-number= number + 1
          %span.step-text.hidden-xs= checkout_step.capitalize
        %li.step-divider
      - else
        = link_to wizard_path(checkout_step, editing: true), class: 'step' do
          %span.step-number= number + 1
          %span.step-text.hidden-xs= checkout_step.to_s.capitalize
        %li.step-divider
  = form_tag wizard_path, method: :patch do
    %h3.general-subtitle Payment
    .hidden-xs.mb-res-50
      %table.table.table-hover
        %thead
          %tr
            %th.col-method
              %span.in-grey-600.ml-40 Method
            %th
              %span.in-grey-600 Days
            %th
              %span.in-grey-600 Price
        %tbody
          - @form.deliveries.each do |delivery|
            %tr
              %td
                .form-group.radio.mt-0.mb-0
                  %label.radio-label
                    = radio_button_tag :delivery, delivery.id, false, class: 'radio-input', hidden: 'true', checked: (delivery == current_order.delivery)
                    %span.radio-icon
                    %span.radio-text= delivery.title
              %td
                %span #{delivery.optimistic_days} to #{delivery.pesimistic_days} days
              %td
                %span.price.font-16.in-gold-500 €#{delivery.price}
    .general-text-align
      %p.in-gold-500.font-18= t('orders.order_summary')
      %table.general-summary-table
        = render 'order_steps/price'
    .text-center
      = submit_tag t('orders.save_and_continue'), class:'btn btn-default mb-20'

app/views/order_steps/fast_sign.html.haml
%main.container.general-main-wrap
  .col-md-6
    .text-center
      %h3.in-gold-500.general-login-title= t('users.returning_customer')
      = link_to user_facebook_omniauth_authorize_path(checkout: 'true'), class: 'general-login-icon' do
        %i.fa.fa-facebook-official
      %p.general-login-text= t('general.or')
    = form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: 'log-in general-form'}) do |f|
      = f.hidden_field :checkout, value: 1
      .form-group.mb-30.field
        = f.label :email, html: {:class => 'control-label input-label', 'data-bar' => t('users.privacy.enter_email')}
        = f.email_field :email, autofocus: true, id: 'email', class: 'form-control', placeholder: t('users.privacy.enter_email')
      .form-group.mb-30
        = f.label :password, html: {:class => 'control-label input-label', 'data-bar' => t('users.privacy.enter_password')}
        = f.password_field :password, autocomplete: false, class: 'form-control', placeholder: t('general.password')
      .text-center
        = f.submit t('layout.links.login'),  class: 'btn btn-default mb-20'
  .col-md-6
    .text-center
      %h3.in-gold-500.general-login-title= t('users.new_customer')
      = link_to user_facebook_omniauth_authorize_path(checkout: 'true'), class: 'general-login-icon' do
        %i.fa.fa-facebook-official
      %p.general-login-text= t('general.or')
    = form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: 'sign-up general-form'}) do |f|
      .form-group.mb-30.field
        = f.hidden_field :checkout, value: 1
        = f.label :email, html: {:class => 'control-label input-label', 'data-bar' => t('users.privacy.enter_email')}
        = f.email_field :email, autofocus: true, id: 'email', class: 'form-control', placeholder: t('users.privacy.enter_email')
      .text-center
        = f.submit t('layout.links.signup'), class: 'btn btn-default mb-20'